using System;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Provides functionality for handling UI fading effects with customizable duration and fade settings.
/// </summary>
public static class FadeUI
{
    private static Image _background;
    private static Color _fadeColor;

    private static float _currentDuration;
    private static float _timer;
    private static float _multiplier;
    private static CoroutineCaller _caller;
    private static int _frontLayderIndex = 10;
    #region Initialize Methods
    /// <summary>
    /// Initializes the fade UI by creating an Image component and setting it up in the scene.
    /// </summary>
    private static void Initialize()
    {
        _caller = CoroutineCaller.Instance;
        Camera camera = Camera.main;
        Canvas canvas = new GameObject("FadeCanvas (Autogenerated)").AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.gameObject.layer = _frontLayderIndex;
        canvas.sortingOrder = 10;
        _background = new GameObject("FadeUI (Autogenerated)").AddComponent<Image>();
        _background.transform.SetParent(canvas.transform, false);
        _background.gameObject.layer = _frontLayderIndex;
        Material mat = new Material(Shader.Find("UI/Default"));
        mat.name = "Material AutoGenerated";
        _background.material = mat;
        SetImageSize(_background.transform as RectTransform);
        _fadeColor = Color.black;
        _fadeColor.a = 1;
        _background.color = _fadeColor;
    }
    private static void SetImageSize(RectTransform rectTransfrom)
    {
        rectTransfrom.anchorMin = Vector2.zero;
        rectTransfrom.anchorMax = Vector2.one;
        rectTransfrom.sizeDelta = Vector2.zero;
    }
    #endregion
    #region Public Methods
    /// <summary>
    /// Starts the fading effect over a specified duration. 
    /// Optionally, <see cref="FadeSettings"/> can be provided, including the percentage of time spent fully black during the fade.
    /// </summary>
    /// <param name="fadeSettings">The settings for the fade effect, including duration and black screen time percentage. Note: Color customization is currently disabled.
    /// <param name="actionAfterFade"> An optional action to execute at end of fade. </param>
    /// If null, it will use the default settings. Color change is currently disbaled </param>
    public static void Fade(FadeSettings? fadeSettings = null, Action actionAfterFade = null, Action actionInTheMiddle = null)
    {
        if (_background == null)
            Initialize();
        FadeSettings settings = fadeSettings ?? FadeSettings.standar;
        _currentDuration = settings.duration;
        // Disabled color assignment for now. This can be re-enabled in the future if color customization is needed.
        /*_fadeColor = settings.color;*/
        _fadeColor.a = 0;
        _timer = 0;
        float blackDuration = _currentDuration * settings.blackDurationPercentage / 100;
        _multiplier = _currentDuration / (_currentDuration - blackDuration);
#if UNITY_EDITOR || DEVELOPMENT_BUILD
        FadeLogger.DebugLog($"Do Fade {Time.time} with {_currentDuration}");
#endif
        if (_multiplier < 1)
            _multiplier = 1;
        _caller.CoroutineUpdateUntil(IsFading, actionAfterFade);
        if (actionInTheMiddle != null)
            _caller.CoroutineExecuteActionAfter(actionInTheMiddle, _currentDuration / 2);
    }
    /// <summary>
    /// Starts a fade-in effect over a specified duration. 
    /// The screen gradually transitions from fully visible to fully black.
    /// </summary>
    /// <param name="duration">The duration of the fade-in effect, in seconds. Default is 1 second.</param>
    /// <param name="color">The fade color. Note: Color customization is currently disabled. </param> 
    /// <param name="actionAfterFade">An optional action to execute at the end of the fade-in effect. 
    /// If null, no additional action will be executed after fading in.</param>
    public static void FadeIn(float duration = 1, Color color = default, Action actionAfterFade = null)
    {
        if (_background == null)
            Initialize();
        // Disabled color assignment for now. This can be re-enabled in the future if color customization is needed.
        /*if (color == default)
              color = _background.color;
          color.a = _fadeColor.a;
        _fadeColor = color;*/
#if UNITY_EDITOR || DEVELOPMENT_BUILD
        FadeLogger.DebugLog($"Do Fade In {Time.time} with {duration}");
#endif
        _currentDuration = duration;
        _timer = 0;
        _caller.CoroutineUpdateUntil(() => IsFading(0, 1), actionAfterFade);
       
    }
    /// <summary>
    /// Starts a fade-out effect over a specified duration. 
    /// The screen gradually transitions from fully black to fully visible.
    /// </summary>
    /// <param name="duration">The duration of the fade-out effect, in seconds. Default is 1 second.</param>
    /// <param name="color">The fade color. Note: Color customization is currently disabled. </param> 
    /// <param name="actionAfterFade">An optional action to execute at the end of the fade-out effect. 
    /// If null, no additional action will be executed after fading out.</param>
    public static void FadeOut(float duration = 1,Color color = default, Action actionAfterFade = null)
    {
        if (_background == null)
            Initialize();
        // Disabled color assignment for now. This can be re-enabled in the future if color customization is needed.
        /*if(color == default)
              color = _background.color;
          color.a = _fadeColor.a;
        _fadeColor = color;*/
#if UNITY_EDITOR || DEVELOPMENT_BUILD
        FadeLogger.DebugLog($"Do Fade Out {Time.time} with {duration}");
#endif
        _currentDuration = duration;
        _timer = 0;
        _caller.CoroutineUpdateUntil(() => IsFading(1, 0), actionAfterFade);
    }
    #endregion
    private static bool IsFading(float from, float to)
    {
        if (_background.color.a == to)
        {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
            FadeLogger.DebugWarning("Fade is alredy setted");
#endif
            return false;
        }
        _timer += Time.deltaTime;
        float fixedTime = _timer / _currentDuration;
        float smoothTime = Mathf.Lerp(from, to, fixedTime);
        _fadeColor.a = smoothTime;
        _background.color = _fadeColor;
        return _timer <= _currentDuration;
    }

    private static bool IsFading()
    {
        _timer += Time.deltaTime;
        float fixedTime = _timer / _currentDuration;
        float smoothTime = Mathf.Sin(fixedTime * Mathf.PI) * _multiplier;
        _fadeColor.a = smoothTime;
        _background.color = _fadeColor;
        return _timer <= _currentDuration;
    }
}
/// <summary>
/// Contains settings for controlling the fade effect.
/// </summary>
/// <note>
/// The <see cref="FadeSettingsDrawer"/> class is used to draw the `FadeSettings` fields in the Inspector using a custom property drawer.
/// Any changes to the serialized fields will not be automatically reflected in the Inspector unless the 
/// <see cref="FadeSettingsDrawer"/> is updated accordingly. If you add or modify any variables in `FadeSettings`,
/// ensure the <see cref="FadeSettingsDrawer"/> logic is also updated to properly display and handle them in the Inspector.
/// </note>
[Serializable]
public struct FadeSettings
{
    public float duration;
    public float blackDurationPercentage;
    public Color color;
    private static readonly FadeSettings defaultFade = new FadeSettings(1, 0f, Color.black);

    public FadeSettings(float duration, float blackDurationPercentage, Color color = default)
    {
        this.duration = duration;
        this.blackDurationPercentage = blackDurationPercentage;
        this.color = color = default ? Color.black : color;
    }
    public static FadeSettings standar => defaultFade;
}
